[holomapping]
files = [
    "*/**",

    # exclude CI and developer assets
    "!.github/",
    "!.vscode/",
    "!cypress/",
    "!docs/",
    "!fixtures/",
    "!habitat/",
    "!helm-chart/",
    "!php-config/Git.config.d/",
    "!script/",
]
after = "*"
