#!/bin/bash

# script/seal-secrets: Seal secrets from given directory

set -e
cd "$(dirname "$0")/.."


# validate input
SECRETS_DIR="${1?'Usage: script/seal-secrets <directory>'}"

if [ ! -d "${SECRETS_DIR}" ]; then
    echo "Directory not found: ${SECRETS_DIR}" 1>&2
    exit 1
fi

if [ -z "${SEALED_SECRETS_CERT}" ]; then
    echo "SEALED_SECRETS_CERT must be set and exported" 1>&2
    exit 1
fi


# seal all secrets in <directory> to helm chart
for input_file in "${SECRETS_DIR}/"*.yaml; do
    output_file="$(basename "${input_file}")"
    echo "Sealing: ${input_file}"
    kubeseal \
        --scope cluster-wide \
        -f "${input_file}" \
        -w "helm-chart/templates/secrets/${output_file}"
done
