apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mailchimp
spec:
  encryptedData:
    MAILCHIMP_API_KEY: AgBBIV1lj6JxIddizc8+cQoeDKaeIarxwmr+/xrlOJ0waon+lsvzfEbpPox40Na4F8S5Uu4958+MoEINCB07JLtVs16UckMoaLT7puCBcnpMimaw4gsoY9/4OnCnPhmmW19jpMuo6Yg1g916JMrGOVBuywjxFgHYPwRl3d0JdLv7CSLBv+4CEWBBu36DDCsh2gH6QN7AZzrCMWxa6JmK81WaCXwZApdb+cjOw7JOacwzdghj1Ygp/u8TppfCga3ZkexDEaPOoQKJs++KDlSjwbN53kHr2PVdyjsLJT3yKrsx6MJyxBYxCDoewGfqBtpiDqxXberHmGHv7VBxWvVWl0nxT4xqyu9x5+1gawPS7dFB87X44GW1+mx2qzq+3BA7lAz6myUzv75tnEpiDE5YQp+L2h2e18rlV/H9BywpfuxKbsD3vIYiFpgDNJHrmxzPty8KobNDsy1l1ypEjmihnK8dkxPLg55mLETvb929udJtUGNBM5vHdl7fjlUZ3Kg465+q14tB6VESnO2VYdRY2yje91tutSjxfrBworl08ouezHLbGg6MMkQcph41tEeY4QrMdrr4Ep1Y7b9OZnvm03CB5yDIyLbbaiBWreWsHIaJoTY3puQqs5DzXyBb2PQbJxIXadsox+byewalwR81fZxE7ydc/s5sFIMZmfjy5AhbWeCdTZvlPd32VdAulAl3/HdyCMHm2ecmTTEIwnhVpOI7TjSiU/MyodZJJj2G32lDFlCvUy4=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mailchimp

