apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mailchimp
  namespace: '{{ .Release.Namespace }}'
spec:
  encryptedData:
    MAILCHIMP_API_KEY: AgA1bgU1suitP2p5+xXHll5kcvcJ98yfJC+e5HZAeNCq6yUhjHF/f3KSdqnpqkjEnjiP8lZtctNEobETQPOVIcKo4mTObyLZpwWy9537qPynG2bgWYZq3BenLHvADxDr9oiyLvAK0QZXKeoJIytvrXFqZ0YwsMkZQtmLArRs8pq5jDWNymbRsGm6XE/P/VoI1RFXkhm1DGZGoHOy9y0fwiS4yhFsQVDbG8p74ypxZ0UQkHIHgT+p0bW4jF5pJNoUgxvRP0cLE2/8euhS/44FWIPL45qJwBRD5yNqWH9vScHjndhY1cviZUfHrlEgXMScWrc+NfsgGqrIhMamGZbZOAfmfbmJ/vF5lG8Aini7L5y79bcnNxZP66+DoG81ibfVx7uAbQitecgU4ZjH1ULCDNq6DahsDcG/3SKpURMMmA+sA3VvZJ+RXBVjl33a39ajMwyPLjujz7D/CSqot7kdv9bT/B6T7etzk4wIXtEjTQ10srhDRcUBhx5UzygtuvkbSTsRJvVkhk2v5HYoA+U1N3WS1+/g6CUqrfg9HYROxPOqEwFSS30bSU0jfjAVW0OnB0BRGagVf6uKlFC6E8CCPgEYgTJbG91L0p8gSRR7HQfZDGrkCpc9ThvvWtCPh0OcnGVazM4u40ozb5/XZ/XKUoaWIHtUk9IYLjuuy1RIb0iGDTuIxp2UJWSi4C9RAo11zHck0aL92vwESAZ62vkEt0CP48SBOHTygulJZssboYzVdAw7wjs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mailchimp
      namespace: '{{ .Release.Namespace }}'

