apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: recaptcha
spec:
  encryptedData:
    RECAPTCHA_SECRET_KEY: AgCq8wdJ/59wPBOAvbqwMKfbOkuCmsvINgUITqFUMPsum3xE2vROu3GK17mBOQpjY4OTwEtlBkYh+hMW9iyZJJrqL6GxWsg++/PeA9no/eZ1XGvk4dVLVES5awWCyRD4iM+XJlYWn7EofAxXXPxz53In50UlwvRQ5pYsKHfP14PvAErSytNO/HOBvjdHfdJ73yKzti8gDkiAhhKV0BSykWypZR2Ggn/D8PZqPt2EB0IDvzoD87Ly+kjSW0CeneDtatjfHFpBpSV4XhldnKTNZTgdBISAq/YGcEB/rzGjshqZJr5BmK7Eoa5WC/bw/QgGy36Pjy/sGCCdrPoOPn1gu7ba33YX/ZGv3/AoZoWbIREj36FnKsbIx0qkjz5vWeslfrRaleBPsthNrPQw7xFShKluIE6W31xE43L7S0zM+FMS4/3Hw8lniKAen73Ea6pXNl2irJ8FH6KQzBCc4md5Tvj/ktqDEhPAzO9jH9MFdmLlGbMrGZ8Se61MaZqZYFiXQ9dFUSkFyr+8fWeHAduHxK39DRNE0VVmwTObMuoNvPo5SmzTwqk2UyUkczqwuaGZhhzPbbPG3SRsA0eKvkiEq7UfJY0iAUFS68MkqvPqC4gg474hP0sNTFhaDpK3WkHxkttqMPRnbBMx83yGo8+6IG+qgqDn7zMjr08jiJBCTHleG75NBIuC0rlBvikFknaPKsjakNbQAQfbwD/hSLOfskPv4Gxt3WtlWCra2UYiJFDNAZ3Vab8z3lIM
    RECAPTCHA_SITE_KEY: AgBh3/WE7n6OGEJ41Otb+bXHVa/aq1IQL+EUugdyYO/LdmpTTqaNnAFTh8ThC4VeDoVY9d5bm3Etjgy6KnD5fcdebQfmP9u4YXA8SwM92nAFnhvtIMkyaxEoIseIcmU2fnhYm2tKiHlUn9s4B/JCbKvJvoMTViM36vYg37/lcqQy35AdqBWaou7CjHvXo0ztWptg2hL9wy7Upn9IU13nqCgzh0rSkaZBFFAtUaY35qewKeOq6RoT9/ZHLd9mi7bPvo7auQN6MpFxZgzTSUJXj+S9+3V3BuhVofd2Qx7CYZfI+YVq1QdcGVBB2L5ObVyajhG2YnWP1cYdbe9EhB8IfrWPNTxU4Ekik154gPgn7B17bKl5JrXG/NC/hOvPHIjj9mXgFve9mBqLZO+16+pk7G8YlMSEjY1Lhc9dEA7XeHWX+IT55OnmvesPsIlhcFHTMfU6A5ox3mz9n6tX1TIMtR4ZhLtvk+VwMaIfHEhdnR2gDLdxMhBQRO9VhecKJWmWQ1Q2NTva4Z7NU+1f48k8GmpCnH5GrChKnrvpwvwPfkxJ7tSxT1X2aodMiAFPExkEjrFQc68cynNLOolB22o34jFuIjPEc/fCKvShVdS1tOSS8irXHTZwg3vG54QzXoGVd9whZB5i6awcr6JDh/2wcVWwYKLyi+XuG1MGGK+mcM3Via6zJcQ9JA8JvQo8KFmPsqqKxukAH3yi/LrznKDcrgSEUfQr6Tb4xaxnUEChsFTYtbS66WLK7G42
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: recaptcha

